version: 2.1

orbs:
  jq: circleci/jq@2.2.0
  aws-cli: circleci/aws-cli@3.1.4
  terraform: circleci/terraform@3.1

executors:
  app-executor:
    docker:
      - image: circleci/node:14.18.1
    working_directory: ~/repo
  
  terraform-executor: 
    docker:
      - image: hashicorp/terraform:latest
aliases:  
  - &show-current-branch
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  
  - &install-dependencies
    run:
      name: Install Dependencies
      command: |
        mkdir -p artifacts

  - &setup-aws-oidc
      name: Get short-term credentials
      command: |
        STS=($(aws sts assume-role-with-web-identity --role-arn ${AWS_ROLE_ARN} --role-session-name "CircleCI-${CIRCLE_BUILD_NUM}" --web-identity-token "${CIRCLE_OIDC_TOKEN}" --duration-seconds 900 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))
        echo "export AWS_ACCESS_KEY_ID=${STS[0]}" >> $BASH_ENV
        echo "export AWS_SECRET_ACCESS_KEY=${STS[1]}" >> $BASH_ENV
        echo "export AWS_SESSION_TOKEN=${STS[2]}" >> $BASH_ENV

jobs:
  testconnection:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: *setup-aws-oidc
      - run:
          name: Test AWS connection
          command: aws s3 ls

  setup:
   executor: app-executor
   steps:
      - checkout
      - *show-current-branch
      - *install-dependencies
      - run:
          name: Copy Terraform folder for EKS module
          command: cp -r eks artifacts/eks/
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  terraform-validate:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch
      -  run:
          name: Code Quality
          command: |
             cd eks/
             terraform init -backend=false
             terraform validate
             terraform fmt -check

  terraform-plan-and-apply-eks:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - *show-current-branch
      -  run:
          name: Terraform Plan [EKS]
          command: |
            cd artifacts/eks/
            terraform init -input=false -backend-config=backend.tfvars
            terraform plan -out=eks.tfplan -var-file=sample.tfvars -input=false
      -  run:
          name: Terraform Apply [EKS]
          command: |
            cd artifacts/eks/
            terraform apply -input=false eks.tfplan
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: terraform create destroy plan
          command: |
            cd artifacts/eks/
            terraform plan -destroy -out tfdestroy -var-file sample.tfvars
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: terraform destroy
          command: |
            cd artifacts/eks/
            terraform apply -auto-approve tfdestroy


workflows:
  argocd-eks-setup:
    jobs:
      - testconnection:
          context: calvine-cloudonmymind

      - setup:
          requires:
            - testconnection

      - terraform-validate:
          context: calvine-cloudonmymind
          requires:
            - setup
          # filters:
          #   branches:
          #     only:
          #       - main
      - terraform-plan-and-apply-eks:
          context: calvine-cloudonmymind
          requires:
            - testconnection
            - terraform-validate
          # filters:
          #   branches:
          #     only:
          #       - main
      - plan-destroy:
          requires:
            - testconnection
            - terraform-plan-and-apply-eks
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
